---
- name: Setup Wordpress
  hosts: server
  remote_user: root
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
   - name: install dependencies packages
     yum: 
      name:
       - httpd
       - unzip
       - wget
       - epel-release
       - python
       - MySQL-python
      state: present
   
   - name: install mariadb
     yum :
      name:
       - mariadb
       - mariadb-server
      state: present

   - name: install php
     yum: 
      name:
       - php
       - php-common
       - php-mysql
       - php-gd
       - php-xml
       - php-mbstring
       - php-mcrypt
       - php-xmlrpc
      state: present
     
   - name: start and enable httpd service
     service: 
      name: httpd
      state: started
      enabled: yes
 
   - name: start and enable mariadb service
     service:
      name: mariadb
      state: started
      enabled: yes
 
   - name: manage firewall add http service
     firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled

   - name: check config
     shell: mysql -u root -e 'exit'
     register: check
     ignore_errors: yes
   
   - name: create new database
     block:
      - name: delete user
        mysql_user:
         name: ''
         login_host: localhost
         login_user: root
         host_all: yes
         state: absent
      - name: revoke access 
        shell: mysql -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
      - name: drop test database
        mysql_db:
         name: test
         login_host: localhost
         login_user: root
         state: absent
      - name: revoke privileges of test user
        shell: mysql -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"
      - name: reload grant table
        shell: mysql -u root -e "Flush privileges;"
      - name: update root password
        mysql_user:
         name: root
         password: "{{ db_root_password }}"
         host_all: yes
     when: check.rc == 0
     
   - name: create wordpress database
     mysql_db:
      login_host: localhost
      login_user: root
      login_password: "{{ db_root_password }}"
      name: "{{ db_name }}"
      state: present
 
   - name: create user ansible
     mysql_user:
      login_host: localhost
      login_user: root
      login_password: "{{ db_root_password }}"
      name: "{{ db_username }}"
      password: "{{ db_password }}"
      priv: '{{ db_name }}.*:ALL'
      state: present
   
   - name: curl wordpress site
     get_url: 
      url: https://wordpress.org/wordpress-5.0.tar.gz
      dest: /home/centos
   
   - name: extract wordpress zip file
     unarchive:
      src: /home/centos/wordpress-5.0.tar.gz
      dest: /var/www/html/
      remote_src: yes
   
   - name: manage file permission
     file: 
      path: /var/www/html/wordpress
      owner: apache
      group: apache
      mode: '0755'
     
   - name: make uploads directory
     file: 
      path: /var/www/html/wordpress/wp-content/uploads
      state: directory
      recurse: yes
      group: apache
   
   - name: copy config file 
     copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        mode: preserve
        owner: apache
        group: apache
        remote_src: yes

   - name: Change default configuration
     lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
     loop:
        - { 
            regexp: ^define\('DB_NAME', line: "define('DB_NAME', '{{ db_name }}');" 
          }
        - { 
            regexp: ^define\('DB_USER', line: "define('DB_USER', '{{ db_username }}');" 
          }
        - { 
            regexp: ^define\('DB_PASSWORD', line: "define('DB_PASSWORD', '{{ db_password }}');" 
          }
        - { 
            regexp: ^define\('DB_HOST', line: "define('DB_HOST', '{{ db_host }}');" 
          }
